### ISSUE TITLE
Some UpdateEntry not load.

### ISSUE THREAD

**Issue by xnhw01** [worstenbrood/HuaweiUpdateLibrary#1]
I want to extract an oeminfo.img from UPDATE.APP. At the first, I try HuaweiUpdateExtractor(HUE) to do that, but I cant see oeminfo.img listed by HUE. Then I found here from your xda thread. Hence I try to use this lib to write a tool to do that. However, I found that the UpdateEntry of oeminfo.img (and many other img in UPDATE.APP) cant be load.

**Comment by worstenbrood** [comment]
Are you sure it is in the update.app?

**Comment by ralshammrei2** [comment]
Yes plz sure it is in the update.app
